---
- name: Install Apache
  hosts: "{{ HOSTS }}"
  become: yes
  vars:
    source_file: ./index.html
    destin_file: /var/www/html

  tasks:

  - name: Show LINYX DIST
    debug: var=ansible_os_family  

  - block:     #=====For Debian========
  
      - name: install server
        package: name=apache2 state=latest

      - name: delete default index page
        file: name=/var/www/html/index.html state="absent" 

      - name: copy file
        copy: src={{ source_file }} dest={{ destin_file }} mode=0555
        notify: Restart apache
 
    when: ansible_os_family == "Debian"

  handlers:
  - name: Restart apache
    service: name=apache2 state=restarted
