---
- name: Polices password
  hosts: prod_servers
  become: yes

  tasks:

  - name: Update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600  
  - name: install pwdqality
    apt: name=libpam-pwquality,cracklib-runtime state=latest

  - name: copy file
    copy: src="./polices/common-password" dest="/etc/pam.d/common-password" mode=0644

  - name: Change password on next login
    shell: passwd -e {{ inventory_hostname }}

